server:
  port: 9090
spring:
  application:
    name: config-server
  cloud:
      config:
        server:
          git:
            uri: https://github.com/Caojiahai1/SpringCloudDemo.git
            search-paths: config

