server:
  port: 9090
spring:
  application:
    name: config-server
  cloud:
      config:
        server:
          git:
            uri: https://github.com/Caojiahai1/SpringCloudDemo.git
            search-paths: config  #配置文件存放目录 Git仓库根目录
            clone-on-start: true  #启动时就clone仓库到本地，默认是在配置被首次请求时，config server才会clone git仓库
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka
  instance:
      instance-id: config-1 #此实例注册到eureka服务端的唯一的实例ID
      prefer-ip-address: true #是否显示IP地址
      leaseRenewalIntervalInSeconds: 10 #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
      leaseExpirationDurationInSeconds: 30 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒

